/**
 * Taskar Bayanai na Markazi (Markaz Knowledge Database)
 * مركز محمد بن إبراهيم آل الشيخ رحمه الله
 */

const INITIAL_DATA = {
  markazInfo: {
    nameAr: "مركز محمد بن إبراهيم آل الشيخ رحمه الله للعلوم الشرعية",
    nameHa: "Cibiyar Sheikh Muhammad bin Ibrahim Aal Al-Sheikh Domin Ilimin Addinin Musulunci",
    nameEn: "Sheikh Muhammad bin Ibrahim Aal Al-Sheikh Islamic Center",
    taglineAr: "منارة لنشر العلم الشرعي المؤصل على منهج الكتاب والسنة",
    taglineHa: "Hasken yada ingantaccen ilimin addinin Musulunci bisa koyarwar Alkur'ani da Sunnah",
    taglineEn: "A beacon for authentic Islamic knowledge based on the Quran and Sunnah",
    directorAr: "إبراهيم شريف أبوبكر",
    directorHa: "Sheikh Ibrahim Sharif Abubakar",
    directorEn: "Sheikh Ibrahim Sharif Abubakar",
    directorTitleAr: "رئيس المركز والمشرف العام",
    directorTitleHa: "Shugaban Cibiyar & Babban Mai Kulawa",
    directorTitleEn: "Director & General Supervisor",
    directorBioAr: "باحث شرعي ومؤلف، المشرف العام على البرامج العلمية والمؤلفات والدروس المنهجية بمركز محمد بن إبراهيم آل الشيخ رحمه الله.",
    directorBioHa: "Babban malami, mai binciken ilimi da wallafe-wallafe, kuma babban mai kula da darussa da tsare-tsaren ilimi na Cibiyar Sheikh Muhammad bin Ibrahim Aal Al-Sheikh.",
    directorBioEn: "Islamic scholar, researcher, and author overseeing the academic curricula, publications, and lectures at the Markaz.",
    location: "Kaduna / Nigeria",
    contactEmail: "info@markaz-alsheikh.org",
    contactPhone: "+234 800 000 0000",
    whatsappGroupUrl: "https://chat.whatsapp.com/GaPNys0J4A05hBXxJDj3V2",
    establishedYear: 1446
  },

  categories: [
    { id: "all", nameAr: "جميع الأقسام", nameHa: "Dukkan Bangarori", nameEn: "All Categories", icon: "📚" },
    { id: "director", nameAr: "مؤلفات الشيخ إبراهيم شريف", nameHa: "Wallafe-Wallafen Sheikh Ibrahim Sharif", nameEn: "Publications by Sheikh Ibrahim Sharif", icon: "⭐" },
    { id: "upcoming", nameAr: "إصدارات قادمة (قريباً)", nameHa: "Littattafai Masu Fitowa (قريباً)", nameEn: "Forthcoming Publications", icon: "✨" },
    { id: "aqeedah", nameAr: "العقيدة والتوحيد", nameHa: "Aqeedah & Tauhidi", nameEn: "Creed & Tawheed", icon: "🧭" },
    { id: "hadith", nameAr: "الحديث وعلومه", nameHa: "Hadisi & Iliminsa", nameEn: "Hadith & Its Sciences", icon: "📜" },
    { id: "tafseer", nameAr: "التفسير وعلوم القرآن", nameHa: "Tafseeri & Alkur'ani", nameEn: "Tafsir & Quran Sciences", icon: "📖" },
    { id: "fiqh", nameAr: "الفقه وأصوله", nameHa: "Fiqhu & Usulinsa", nameEn: "Jurisprudence & Principles", icon: "⚖️" },
    { id: "seerah", nameAr: "السيرة النبوية والتاريخ", nameHa: "Seerah & Tarihi", nameEn: "Prophetic Biography & History", icon: "🕌" },
    { id: "fatawa", nameAr: "فتاوى ورسائل وتراجم", nameHa: "Fatawoyi da Tarihi", nameEn: "Fatawa, Treatises & Biographies", icon: "🖋️" },
    { id: "arabic", nameAr: "اللغة العربية والآداب", nameHa: "Harshen Larabci & Adabi", nameEn: "Arabic Language & Grammar", icon: "🔤" },
    { id: "lessons", nameAr: "دروس ودورات المركز", nameHa: "Darussan Cibiyar (Markaz)", nameEn: "Center Lessons & Courses", icon: "🎓" }
  ],

  books: [
    // --- Published Grand Encyclopedic Editions by Sheikh Ibrahim Sharif Abubakar ---
    {
      id: "b_durar_al_bahiyyah",
      titleAr: "الدُّرَرُ البَهِيَّةُ فِي إِيضَاحِ وَتَحْقِيقِ القَوَاعِدِ الأَرْبَعِ العَقَدِيَّةِ",
      titleHa: "Ad-Durarul Bahiyyah fi Idahi wa Tahqiqil Qawa'idil Arba'il Aqadiyyah (Littafi na 1)",
      titleEn: "Ad-Durar al-Bahiyyah: Comprehensive Commentary on the Four Foundations of Creed (Vol. 1)",
      authorAr: "إبراهيم شريف أبوبكر",
      authorHa: "Sheikh Ibrahim Sharif Abubakar",
      authorEn: "Sheikh Ibrahim Sharif Abubakar",
      category: "aqeedah",
      pages: 185,
      size: "1.55 MB",
      year: "1448H",
      cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "pdf/1_ad_durar_al_bahiyyah.pdf",
      htmlEditionUrl: "books_html/1_ad_durar_al_bahiyyah.html",
      descriptionAr: "المُجَلَّدُ الكَبِيرُ الأَوَّلُ مِنْ سِلْسِلَةِ المُقَرَّرَاتِ التَّأْصِيلِيَّةِ: الشَّرْحُ الكَبِيرُ المَوْسُوعِيُّ لِلقَوَاعِدِ الأَرْبَعِ العَقَدِيَّةِ عَلَى مَنْهَجِ أَهْلِ السُّنَّةِ وَالجَمَاعَةِ.",
      descriptionHa: "Littafi na Farko a cikin jerin manhajar ilimi ta Markaz: Cikakken shari'ar da bincike mai zurfi kan Littafin Qawa'idul Arba'a a Aqidar Ahlus Sunnah.",
      descriptionEn: "Volume 1 of the Scholarly Curricula: An encyclopedic commentary and verification of the Four Foundations of Islamic Creed.",
      featured: true,
      isUpcoming: false,
      downloads: 3820
    },
    {
      id: "b_nayl_al_amani",
      titleAr: "نَيْلُ الأَمَانِي فِي شَرْحِ وَتَحْقِيقِ مَنْظُومَةِ البَيْقُونِيِّ",
      titleHa: "Naylul Amani fi Sharhi wa Tahqiqi Manzumatil Bayquniyyah (Littafi na 2)",
      titleEn: "Nayl al-Amani: Comprehensive Commentary on the Bayquniyyah in Hadith Terminology (Vol. 2)",
      authorAr: "إبراهيم شريف أبوبكر",
      authorHa: "Sheikh Ibrahim Sharif Abubakar",
      authorEn: "Sheikh Ibrahim Sharif Abubakar",
      category: "hadith",
      pages: 195,
      size: "2.19 MB",
      year: "1448H",
      cover: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "pdf/2_nayl_al_amani.pdf",
      htmlEditionUrl: "books_html/2_nayl_al_amani.html",
      descriptionAr: "المُجَلَّدُ الكَبِيرُ الثَّانِي مِنْ سِلْسِلَةِ المُقَرَّرَاتِ التَّأْصِيلِيَّةِ: الشَّرْحُ الكَبِيرُ المَوْسُوعِيُّ لِمَنْظُومَةِ البَيْقُونِيِّ، يَشْتَمِلُ عَلَى الإِعْرَابِ، وَالتَّحْرِيرِ الاصْطِلَاحِيِّ، وَالأَمْثِلَةِ مِنَ الصَّحِيحَيْنِ.",
      descriptionHa: "Littafi na Biyu a cikin jerin manhajar ilimi ta Markaz: Cikakken shari'ar baitocin Manzumar Al-Bayquniyyah a Ilimin Mustalahul Hadisi tare da i'rabi da misalai.",
      descriptionEn: "Volume 2 of the Scholarly Curricula: Encyclopedic commentary on Manzumat al-Bayquniyyah with grammatical parsing, critical definitions, and applied examples from the Sahihayn.",
      featured: true,
      isUpcoming: false,
      downloads: 4150
    },
    {
      id: "b_fath_ar_rahim",
      titleAr: "فَتْحُ الرَّحِيمِ المَنَّانِ بِشَرْحِ الأُصُولِ الثَّلَاثَةِ مَعَ الدَّلِيلِ وَالبَيَانِ",
      titleHa: "Fathur Rahimul Mannan bi-Sharhil Usulis Salasa ma'ad Dalili wal Bayan (Littafi na 3)",
      titleEn: "Fath al-Rahim al-Mannan: Comprehensive Commentary on the Three Principles (Vol. 3)",
      authorAr: "إبراهيم شريف أبوبكر",
      authorHa: "Sheikh Ibrahim Sharif Abubakar",
      authorEn: "Sheikh Ibrahim Sharif Abubakar",
      category: "aqeedah",
      pages: 68,
      size: "1.78 MB",
      year: "1448H",
      cover: "https://images.unsplash.com/photo-1532012164546-f432f2e3777a?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "pdf/3_fath_ar_rahim_al_mannan.pdf",
      htmlEditionUrl: "books_html/3_fath_ar_rahim_al_mannan.html",
      descriptionAr: "المُجَلَّدُ الكَبِيرُ الثَّالِثُ مِنْ سِلْسِلَةِ المُقَرَّرَاتِ التَّأْصِيلِيَّةِ: الشَّرْحُ الكَبِيرُ المَوْسُوعِيُّ لِثَلَاثَةِ الأُصُولِ وَأَدِلَّتِهَا، مَعَ تَحْقِيقِ المَسَائِلِ الأَرْبَعِ، وَالمُقَدِّمَاتِ الثَّلَاثِ، وَأَنْوَاعِ العِبَادَةِ، وَمَرَاتِبِ الدِّينِ، وَالسِّيرَةِ النَّبَوِيَّةِ.",
      descriptionHa: "Littafi na Uku a cikin jerin manhajar ilimi ta Markaz: Cikakken sharhi mai zurfi da bincike kan littafin Usulus Salasa (Karatun Sanin Allah, Addini, da Manzo SAW tare da cikakkun hujjoji da jadawalan ilimi).",
      descriptionEn: "Volume 3 of the Scholarly Curricula: An encyclopedic commentary on the Three Principles with exhaustive proofs, covering the four foundational matters, the three prefaces, types of worship, ranks of Islam, and prophetic biography.",
      featured: true,
      isUpcoming: false,
      downloads: 4890
    },
    {
      id: "b_al_manhal_as_safi",
      titleAr: "المَنْهَلُ الصَّافِي فِي شَرْحِ وَتَحْقِيقِ قَوَاعِدِ السَّعْدِيِّ الفِقْهِيَّةِ",
      titleHa: "Al-Manhalus Safi fi Sharhi wa Tahqiqi Qawa'idis Sa'diyyah (Littafi na 4)",
      titleEn: "Al-Manhal al-Safi: Comprehensive Commentary on al-Sa'di's Legal Maxims (Vol. 4)",
      authorAr: "إبراهيم شريف أبوبكر",
      authorHa: "Sheikh Ibrahim Sharif Abubakar",
      authorEn: "Sheikh Ibrahim Sharif Abubakar",
      category: "fiqh",
      pages: 45,
      size: "1.60 MB",
      year: "1448H",
      cover: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "pdf/4_al_manhal_as_safi.pdf",
      htmlEditionUrl: "books_html/4_al_manhal_as_safi.html",
      descriptionAr: "المُجَلَّدُ الكَبِيرُ الرَّابِعُ مِنْ سِلْسِلَةِ المُقَرَّرَاتِ التَّأْصِيلِيَّةِ: الشَّرْحُ الكَبِيرُ المَوْسُوعِيُّ لِمَنْظُومَةِ القَوَاعِدِ الفِقْهِيَّةِ لِلسَّعْدِيِّ، مَعَ شَرْحِ جَمِيعِ أَبْيَاتِ المَنْظُومَةِ الـ 46 كَامِلَةً، وَتَأْصِيلِ القَوَاعِدِ الكُبْرَى الخَمْسِ، وَتَفْرِيعَاتِ الفِقْهِ المُقَارَنِ.",
      descriptionHa: "Littafi na Hudu a cikin jerin manhajar ilimi ta Markaz: Cikakken sharhin wakar Ka'idojin Fiqhu ta Sheikh As-Sa'di (baitoci 46 baki daya) da ka'idoji biyar manya da rassan fiqhu a mazhabobi hudu.",
      descriptionEn: "Volume 4 of the Scholarly Curricula: Encyclopedic commentary on Sheikh as-Sa'di's 46-verse didactic poem on Islamic legal maxims, systematically expounding the Five Universal Maxims and comparative jurisprudential branches.",
      featured: true,
      isUpcoming: false,
      downloads: 3670
    },
    {
      id: "b_umdat_al_muwahhid",
      titleAr: "عُمْدَةُ المُوَحِّدِ السَّدِيدِ فِي شَرْحِ كِتَابِ التَّوْحِيدِ الَّذِي هُوَ حَقُّ اللهِ عَلَى العَبِيدِ",
      titleHa: "Umdatul Muwahhidis Sadid fi Sharhi Kitabit Tauhid (Littafi na 5)",
      titleEn: "Umdat al-Muwahhid al-Sadid: Comprehensive Commentary on Kitab al-Tawheed (Vol. 5)",
      authorAr: "إبراهيم شريف أبوبكر",
      authorHa: "Sheikh Ibrahim Sharif Abubakar",
      authorEn: "Sheikh Ibrahim Sharif Abubakar",
      category: "aqeedah",
      pages: 184,
      size: "3.43 MB",
      year: "1448H",
      cover: "https://images.unsplash.com/photo-1532012164546-f432f2e3777a?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "pdf/5_umdat_al_muwahhid.pdf",
      htmlEditionUrl: "books_html/5_umdat_al_muwahhid.html",
      descriptionAr: "المُجَلَّدُ الكَبِيرُ الخَامِسُ مِنْ سِلْسِلَةِ المُقَرَّرَاتِ التَّأْصِيلِيَّةِ: الشَّرْحُ المَوْسُوعِيُّ لِكِتَابِ التَّوْحِيدِ لِلشَّيْخِ مُحَمَّدِ بْنِ عَبْدِ الوَهَّابِ، يَتَضَمَّنُ تَأْصِيلَ أَبْوَابِ التَّوْحِيدِ، وَبَيَانَ الشِّرْكِ الأَكْبَرِ وَالأَصْغَرِ، وَشُرُوطَ لَا إِلَهَ إِلَّا اللهُ، وَسَدَّ ذَرَائِعِ الغُلُوِّ وَالبِدَعِ، وَمَسَائِلَ الإِيمَانِ وَالقَدَرِ.",
      descriptionHa: "Littafi na Biyar a cikin jerin manhajar ilimi ta Markaz: Cikakken sharhi mai zurfi kan Littafin Kitabut Tauhid na Sheikh Muhammad bin Abdulwahhab, yana bayyana rabe-raben Tauhidi, Sharrin Shirk, Sharuddan Kalmar Shahada, da kariya daga bidi'o'i da kaddara.",
      descriptionEn: "Volume 5 of the Scholarly Curricula: Encyclopedic commentary on Imam Muhammad bin Abd al-Wahhab's Kitab al-Tawheed, expounding the fundamentals of Islamic monotheism, major and minor shirk, conditions of the testimony of faith, and refutations of idolatry and fatalism.",
      featured: true,
      isUpcoming: false,
      downloads: 4210
    },

    // --- Verified & Published Markaz Editions (11 Complete PDF Releases) ---
    {
      id: "b_tuhfatul_wildan",
      titleAr: "تُحْفَةُ الوِلْدَانِ مِنْ أَحَادِيثِ النَّبِيِّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ عَنِ القُرْآنِ (المجلد الكامل - الجزء 1 و 2)",
      titleHa: "Tuhfatul Wildan min Ahadithin Nabiyyi (SAW) 'anil Qur'an (Cikakken Littafi - Juzu'i 1 & 2)",
      titleEn: "Tuhfat al-Wildan: Prophetic Hadiths on the Virtues of the Quran (Complete Edition - Vols. 1 & 2)",
      authorAr: "إبراهيم شريف أبوبكر",
      authorHa: "Sheikh Ibrahim Sharif Abubakar",
      authorEn: "Sheikh Ibrahim Sharif Abubakar",
      category: "hadith",
      pages: 106,
      size: "3.84 MB",
      year: "1446H",
      cover: "https://images.unsplash.com/photo-1609599006353-e629aaabfeae?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "pdf/تُحْفَةُ_الوِلْدَانِ_الجزء_الأول_والثاني_Book_1_and_2.pdf",
      htmlEditionUrl: "books_html/6_tuhfatul_wildan.html",
      descriptionAr: "المجلد الكامل لكتاب تحفة الولدان يجمع الجزأين الأول والثاني في فضل تلاوة القرآن الكريم وحفظه وتدبره، يُدرّس في حلقات ودروس المركز يوم الاثنين.",
      descriptionHa: "Cikakken littafi mai albarka wanda ya tattara Juzu'i na 1 da na 2 kan falalar Alkur'ani mai girma, wanda ake karantarwa a ranar Litinin a dandalin Markaz.",
      descriptionEn: "The complete two-volume edition of Tuhfat al-Wildan collecting authentic Hadiths on the recitation, memorization, and virtues of the Holy Quran.",
      featured: true,
      isUpcoming: false,
      downloads: 2150
    },
    {
      id: "b_tuhfatul_wildan_p1",
      titleAr: "تُحْفَةُ الوِلْدَانِ عَنِ القُرْآنِ (الجزء الأول)",
      titleHa: "Tuhfatul Wildan 'anil Qur'an (Juzu'i na 1)",
      titleEn: "Tuhfat al-Wildan (Part 1)",
      authorAr: "إبراهيم شريف أبوبكر",
      authorHa: "Sheikh Ibrahim Sharif Abubakar",
      authorEn: "Sheikh Ibrahim Sharif Abubakar",
      category: "hadith",
      pages: 54,
      size: "1.96 MB",
      year: "1446H",
      cover: "https://images.unsplash.com/photo-1609599006353-e629aaabfeae?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "pdf/تُحْفَةُ_الوِلْدَانِ_الجزء_الأول_Book_1.pdf",
      htmlEditionUrl: "books_html/6_tuhfatul_wildan.html",
      descriptionAr: "الجزء الأول من كتاب تحفة الولدان: الأحاديث الواردة في فضل تلاوة القرآن وتعلمه وتعليمه.",
      descriptionHa: "Sashe na farko na littafin Tuhfatul Wildan mai kunshe da hadisai kan koyo da koyar da Alkur'ani.",
      descriptionEn: "Part 1 of Tuhfat al-Wildan focusing on the virtues of learning and teaching the Quran.",
      featured: false,
      isUpcoming: false,
      downloads: 1320
    },
    {
      id: "b_tuhfatul_wildan_p2",
      titleAr: "تُحْفَةُ الوِلْدَانِ عَنِ القُرْآنِ (الجزء الثاني)",
      titleHa: "Tuhfatul Wildan 'anil Qur'an (Juzu'i na 2)",
      titleEn: "Tuhfat al-Wildan (Part 2)",
      authorAr: "إبراهيم شريف أبوبكر",
      authorHa: "Sheikh Ibrahim Sharif Abubakar",
      authorEn: "Sheikh Ibrahim Sharif Abubakar",
      category: "hadith",
      pages: 53,
      size: "2.01 MB",
      year: "1446H",
      cover: "https://images.unsplash.com/photo-1609599006353-e629aaabfeae?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "pdf/تُحْفَةُ_الوِلْدَانِ_الجزء_الثاني_Book_2.pdf",
      htmlEditionUrl: "books_html/6_tuhfatul_wildan.html",
      descriptionAr: "الجزء الثاني من كتاب تحفة الولدان: فضائل سور وآيات مخصوصة من كتاب الله العزيز.",
      descriptionHa: "Sashe na biyu na littafin Tuhfatul Wildan mai kunshe da falalar kebantattun surori da ayoyin Alkur'ani.",
      descriptionEn: "Part 2 of Tuhfat al-Wildan highlighting virtues of specific surahs and verses.",
      featured: false,
      isUpcoming: false,
      downloads: 1190
    },
    {
      id: "b_alfu_hadith",
      titleAr: "أَلْفُ حَدِيثٍ وَحَدِيثٍ مِنْ صَحِيحِ سُنَنِ خَيْرِ البَرِيَّةِ (النسخة العربية الكاملة - 1001)",
      titleHa: "Alfu Hadithin Wa Hadith min Sahih Sunan Khayril Bariyyah (Hausar Larabci - 1001)",
      titleEn: "1001 Authentic Hadiths from the Sunnah (Full Arabic Edition)",
      authorAr: "إبراهيم شريف أبوبكر",
      authorHa: "Sheikh Ibrahim Sharif Abubakar",
      authorEn: "Sheikh Ibrahim Sharif Abubakar",
      category: "hadith",
      pages: 416,
      size: "8.63 MB",
      year: "1446H",
      cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "pdf/1001_Authentic_Hadith_Arabic.pdf",
      htmlEditionUrl: "books_html/7_alfu_hadith.html",
      descriptionAr: "الموسوعة الحديثية الجامعة لألف حديث وحديث في العقيدة والأحكام والآداب والرقائق، المعتمدة في دروس المركز الأسبوعية (السبت والخميس).",
      descriptionHa: "Babban kundin hadisai 1001 da aka tace daga ingantattun sunnonin Annabi (SAW) a fannoni daban-daban na shari'a da dabi'u.",
      descriptionEn: "The standard Arabic comprehensive compilation of 1001 authentic prophetic traditions across creed, jurisprudence, and manners.",
      featured: true,
      isUpcoming: false,
      downloads: 3120
    },
    {
      id: "b_alfu_hadith_bi",
      titleAr: "أَلْفُ حَدِيثٍ وَحَدِيثٍ (النسخة ثنائية اللغة: عربي - إنجليزي - 1001)",
      titleHa: "Alfu Hadithin Wa Hadith (Bilingual: Larabci da Turanci - 1001)",
      titleEn: "1001 Authentic Hadith (Bilingual Edition: Arabic & English)",
      authorAr: "إبراهيم شريف أبوبكر",
      authorHa: "Sheikh Ibrahim Sharif Abubakar",
      authorEn: "Sheikh Ibrahim Sharif Abubakar",
      category: "hadith",
      pages: 667,
      size: "13.47 MB",
      year: "1446H",
      cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "pdf/1001_Authentic_Hadith_Bilingual.pdf",
      htmlEditionUrl: "books_html/7_alfu_hadith.html",
      descriptionAr: "النسخة الموسعة المتقنة ثنائية اللغة، تشمل النص العربي المشكول مع الترجمة الإنجليزية المقابلة والتخريج العلمي الموثق.",
      descriptionHa: "Cikakkiyar bugun hadisai 1001 a harsuna biyu: Matanin Larabci tare da fassarar Turanci da takhrijin kowane hadisi.",
      descriptionEn: "Comprehensive bilingual edition featuring complete vocalized Arabic text alongside English translations and authenticated references.",
      featured: true,
      isUpcoming: false,
      downloads: 2780
    },
    {
      id: "b_alfu_hadith_en",
      titleAr: "1001 Authentic Hadith from the Sunnah (النسخة الإنجليزية الكاملة)",
      titleHa: "1001 Authentic Hadith (Kamusun Hadisai da Turanci)",
      titleEn: "1001 Authentic Hadith from the Prophetic Sunnah (English Edition)",
      authorAr: "إبراهيم شريف أبوبكر",
      authorHa: "Sheikh Ibrahim Sharif Abubakar",
      authorEn: "Sheikh Ibrahim Sharif Abubakar",
      category: "hadith",
      pages: 344,
      size: "6.54 MB",
      year: "1446H",
      cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "pdf/1001_Authentic_Hadith_English.pdf",
      htmlEditionUrl: "books_html/7_alfu_hadith.html",
      descriptionAr: "الترجمة الإنجليزية الكاملة المعتمدة للموسوعة الحديثية (1001 حديث) مع الفهارس الموضوعية والتبويب الدقيق.",
      descriptionHa: "Fassarar Turanci ta littafin hadisai 1001 domin saukaka fahimta ga masu karatu da dalibai na duniya baki daya.",
      descriptionEn: "Complete English translation of the 1001 Authentic Hadiths collection with thematic indexing and scholarly references.",
      featured: false,
      isUpcoming: false,
      downloads: 1940
    },

    // --- 11 Upcoming Publications by Sheikh Ibrahim Sharif Abubakar ---
    {
      id: "b_isa_1",
      titleAr: "مِشْكَاةُ الرَّائِدِ فِي فَضْلِ العِلْمِ وَعُلُوِّ الهِمَمِ وَآدَابِ القَاصِدِ",
      titleHa: "Mishkatur Ra'id fi Fadlil Ilmi wa Uluwwil Himami wa Adabil Qasid",
      titleEn: "Mishkat al-Ra'id: On the Virtues of Knowledge, High Aspirations, and Etiquette",
      authorAr: "إبراهيم شريف أبوبكر",
      authorHa: "Sheikh Ibrahim Sharif Abubakar",
      authorEn: "Sheikh Ibrahim Sharif Abubakar",
      category: "lessons",
      pages: 210,
      size: "قيد الإعداد",
      year: "1446H - قريباً",
      cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "#",
      descriptionAr: "كتاب نفيس مؤصل في بيان شرف العلم وفضله، والآداب الرفيعة التي يتحلى بها طالب العلم، مع شحذ الهمم نحو معالي الأمور والمقاصد.",
      descriptionHa: "Littafi mai matukar amfani wajen bayyana darajar ilimi, laduban neman ilimi, da hanyoyin daukaka himma ga dalibai da masu neman ilimi.",
      descriptionEn: "A profound scholarly work on the nobility of Islamic knowledge, etiquette of students, and cultivating high aspiration.",
      featured: true,
      isUpcoming: true,
      downloads: 0
    },
    {
      id: "b_isa_2",
      titleAr: "إِفْرَادُ رَبِّ البَرِيَّةِ بِأَنْوَاعِ العُبُودِيَّةِ وَبَيَانُ حَقِيقَةِ الشِّرْكِيَّةِ",
      titleHa: "Ifradu Rabbil Bariyyati bi-Anwa'il Ubudiyyah wa Bayanu Haqiqatish Shirkiyyah",
      titleEn: "Singling Out the Lord of Creation in Acts of Worship and Clarifying Polytheism",
      authorAr: "إبراهيم شريف أبوبكر",
      authorHa: "Sheikh Ibrahim Sharif Abubakar",
      authorEn: "Sheikh Ibrahim Sharif Abubakar",
      category: "aqeedah",
      pages: 280,
      size: "قيد الإعداد",
      year: "1446H - قريباً",
      cover: "https://images.unsplash.com/photo-1532012164546-f432f2e3777a?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "#",
      descriptionAr: "دراسة عقدية مؤصلة في تحقيق توحيد الألوهية والعبادة وإفراد الخالق بالنسك والدعاء، مع كشف أصول الشرك ومظاهره المعاصرة.",
      descriptionHa: "Zurfaffan bincike kan Tauhidin Ibada (Uluhiyyah), da bayyana hakikanin bauta ga Allah da kuma kaucewa kowane nau'in shirka.",
      descriptionEn: "A rigorous theological treatise on the oneness of worship (Tawheed al-Uluhiyyah) and refuting contemporary polytheistic practices.",
      featured: true,
      isUpcoming: true,
      downloads: 0
    },
    {
      id: "b_isa_3",
      titleAr: "سَبِيلُ النَّجَاةِ وَالمَنَارِ فِي عَقِيدَةِ الصَّفْوَةِ الأَخْيَارِ",
      titleHa: "Sabilun Najati wal Manar fi Aqidatis Safwatil Akhyar",
      titleEn: "The Path of Salvation and Beacon in the Creed of the Righteous Predecessors",
      authorAr: "إبراهيم شريف أبوبكر",
      authorHa: "Sheikh Ibrahim Sharif Abubakar",
      authorEn: "Sheikh Ibrahim Sharif Abubakar",
      category: "aqeedah",
      pages: 320,
      size: "قيد الإعداد",
      year: "1446H - قريباً",
      cover: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "#",
      descriptionAr: "كتاب جامع وموجز في مجمل عقيدة أهل السنة والجماعة في الإيمان والأسماء والصفات والقضاء والقدر والصحابة رضي الله عنهم.",
      descriptionHa: "Cikakken kundi kan ingantacciyar Aqidar Ahlus Sunnah wal Jama'ah a cikin rukunnan Imani da Sunaye da Siffofin Allah.",
      descriptionEn: "A comprehensive exposition of the creed of Ahlus Sunnah wal Jama'ah based on the Quran, Sunnah, and consensus of the Salaf.",
      featured: true,
      isUpcoming: true,
      downloads: 0
    },
    {
      id: "b_isa_4",
      titleAr: "فَيْضُ الخَبِيرِ فِي إِيضَاحِ مَعَانِي الأَرْبَعِينَ النَّوَوِيَّةِ بِالتَّيْسِيرِ",
      titleHa: "Faydul Khabir fi Iydahi Ma'anil Arba'inan Nawawiyyah bit-Taysir (Sharhin Hadisai 40)",
      titleEn: "The Outpouring of the All-Aware: A Simplified Commentary on Imam Nawawi's Forty Hadiths",
      authorAr: "إبراهيم شريف أبوبكر",
      authorHa: "Sheikh Ibrahim Sharif Abubakar",
      authorEn: "Sheikh Ibrahim Sharif Abubakar",
      category: "hadith",
      pages: 240,
      size: "قيد الإعداد",
      year: "1446H - قريباً",
      cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "#",
      descriptionAr: "شرح ميسر ومحرر للأحاديث الأربعين النووية، يبرز جوامع الكلم النبوية مع التركيز على استخراج الفوائد الفقهية والتزكوية والتربوية.",
      descriptionHa: "Sharhi mai saukin fahimta ga dalibai da al'umma baki daya kan Hadisan Arba'ina na Imam An-Nawawi tare da darussan tarbiyya.",
      descriptionEn: "A lucid commentary on the Forty Hadiths of Imam al-Nawawi, extracting spiritual insights and legal maxims.",
      featured: true,
      isUpcoming: true,
      downloads: 0
    },
    {
      id: "b_isa_5",
      titleAr: "فَتْحُ الرَّحِيمِ المَنَّانِ بِشَرْحِ الأُصُولِ الثَّلَاثَةِ مَعَ الدَّلِيلِ وَالبَيَانِ",
      titleHa: "Fathur Rahimul Mannan bi-Sharhil Usulis Salasa ma'ad Dalili wal Bayan",
      titleEn: "The Opening of the Merciful: Commentary on the Three Principles with Evidences",
      authorAr: "إبراهيم شريف أبوبكر",
      authorHa: "Sheikh Ibrahim Sharif Abubakar",
      authorEn: "Sheikh Ibrahim Sharif Abubakar",
      category: "aqeedah",
      pages: 68,
      size: "1.78 MB",
      year: "1448H",
      cover: "https://images.unsplash.com/photo-1532012164546-f432f2e3777a?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "pdf/3_fath_ar_rahim_al_mannan.pdf",
      htmlUrl: "books_html/3_fath_ar_rahim_al_mannan.html",
      descriptionAr: "شرح تدريسي مؤصل لمتن ثلاثة الأصول وأدلتها، يوضح معرفة العبد ربه ودينه ونبيه صلى الله عليه وسلم بالأدلة الواضحة.",
      descriptionHa: "Karatun koyarwa mai cike da hujjoji kan littafin Usulus Salasa domin sanin Ubangiji, Addinin Musulunci, da Manzon Allah (SAW).",
      descriptionEn: "A pedagogical explanation of The Three Fundamental Principles detailing knowledge of Allah, Islam, and Prophet Muhammad (PBUH).",
      featured: true,
      isUpcoming: false,
      downloads: 1450
    },
    {
      id: "b_isa_6",
      titleAr: "الدُّرَرُ البَهِيَّةُ فِي إِيضَاحِ القَوَاعِدِ الأَرْبَعِ العَقَدِيَّةِ",
      titleHa: "Ad-Durarul Bahiyyah fi Iydahil Qawa'idil Arba'il Aqdiyyah",
      titleEn: "The Splendid Pearls: Clarifying the Four Principles of Islamic Creed",
      authorAr: "إبراهيم شريف أبوبكر",
      authorHa: "Sheikh Ibrahim Sharif Abubakar",
      authorEn: "Sheikh Ibrahim Sharif Abubakar",
      category: "aqeedah",
      pages: 63,
      size: "1.55 MB",
      year: "1448H",
      cover: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "pdf/1_ad_durar_al_bahiyyah.pdf",
      htmlUrl: "books_html/1_ad_durar_al_bahiyyah.html",
      descriptionAr: "بيان موجز وواضح للقواعد الأربع في توحيد العبادة، لتمييز سبيل الموحدين من شبهات المشركين في كل عصر ومصر.",
      descriptionHa: "Takaitaccen bayani kan ka'idoji hudu na Tauhidi da ke fayyace tsarkakkiyar bautar Allah da raba ta da shirka.",
      descriptionEn: "A precise clarification of the Four Rules in Tawheed distinguishing between pure monotheism and the arguments of polytheism.",
      featured: true,
      isUpcoming: false,
      downloads: 1890
    },
    {
      id: "b_isa_7",
      titleAr: "خُلَاصَةُ الأَفْهَامِ مِنْ جَامِعِ العُلُومِ وَالحِكَمِ لِابْنِ رَجَبِ الإِمَامِ",
      titleHa: "Khulasatul Afham min Jami'il Ulumi wal Hikami li-Ibn Rajab Al-Imam",
      titleEn: "The Essence of Understanding: Abridgment of Jami' al-Ulum wal-Hikam",
      authorAr: "إبراهيم شريف أبوبكر",
      authorHa: "Sheikh Ibrahim Sharif Abubakar",
      authorEn: "Sheikh Ibrahim Sharif Abubakar",
      category: "hadith",
      pages: 350,
      size: "قيد الإعداد",
      year: "1446H - قريباً",
      cover: "https://images.unsplash.com/photo-1507842229451-7f01be7ff6ab?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "#",
      descriptionAr: "تهذيب واختصار نفيس لدرة كتب شروح الحديث 'جامع العلوم والحكم' للحافظ ابن رجب، يبرز معاني جوامع الكلم وفوائدها بأسلوب مقرب.",
      descriptionHa: "Tace da takaita babban littafin Jami'ul Ulumi wal Hikam na Ibn Rajab Al-Hanbali, wajen saukaka samun ilimomin hadisai.",
      descriptionEn: "A refined summary of Ibn Rajab's masterpiece Jami' al-Ulum wal-Hikam, highlighting prophetic wisdom and aphorisms.",
      featured: true,
      isUpcoming: true,
      downloads: 0
    },
    {
      id: "b_isa_8",
      titleAr: "قَطْفُ الجَنَى الدَّانِي مِنْ فَضَائِلِ القُرْآنِ لِلْقَاسِمِ بْنِ سَلَّامٍ الإِمَامِ الرَّبَّانِي",
      titleHa: "Qatful Janad Dani min Fada'ilil Qur'ani lil-Qasim bin Sallam Al-Imamir Rabbani",
      titleEn: "Gathering the Near Fruit: Abridgment of Fada'il al-Qur'an by Abu Ubayd",
      authorAr: "إبراهيم شريف أبوبكر",
      authorHa: "Sheikh Ibrahim Sharif Abubakar",
      authorEn: "Sheikh Ibrahim Sharif Abubakar",
      category: "tafseer",
      pages: 260,
      size: "قيد الإعداد",
      year: "1446H - قريباً",
      cover: "https://images.unsplash.com/photo-1609599006353-e629aaabfeae?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "#",
      descriptionAr: "تقريب واختصار لواحد من أقدم وأجلّ مصنفات علوم القرآن وفضائله للإمام أبي عُبيد القاسم بن سلام، مع حذف الأسانيد وتيسير المتون.",
      descriptionHa: "Takaitaccen littafin Falalar Alkur'ani na babban malamin da Abu Ubaid Al-Qasim bin Sallam, mai cike da nassosin darajar Alkur'ani.",
      descriptionEn: "An accessible condensation of one of the earliest classical manuscripts on the virtues and recitations of the Holy Quran.",
      featured: false,
      isUpcoming: true,
      downloads: 0
    },
    {
      id: "b_isa_9",
      titleAr: "صَفْوَةُ المَنْهَلِ مِنْ كِتَابِ المَدْخَلِ لِابْنِ الحَاجِّ المَالِكِيِّ المُبَجَّلِ",
      titleHa: "Safwatul Manhali min Kitabil Madkhali li-Ibnil Haajj Al-Malikiyyil Mubajjal",
      titleEn: "The Purest Spring: Abridgment of Al-Madkhal by Ibn al-Hajj al-Maliki",
      authorAr: "إبراهيم شريف أبوبكر",
      authorHa: "Sheikh Ibrahim Sharif Abubakar",
      authorEn: "Sheikh Ibrahim Sharif Abubakar",
      category: "fiqh",
      pages: 380,
      size: "قيد الإعداد",
      year: "1446H - قريباً",
      cover: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "#",
      descriptionAr: "مختصر جامع لمباحث السنن والآداب والتحذير من البدع والمحدثات الواردة في كتاب المدخل الشهير للعلامة ابن الحاج الفاسي المالكي.",
      descriptionHa: "Cikakken zaben darussan sunnoni, kyawawan ladubba da gargadi kan bidi'o'i daga shahararren littafin Al-Madkhal na Ibnul Haaj.",
      descriptionEn: "An abridged edition synthesizing the practical Sunnah, manners, and cautions against innovations from Al-Madkhal.",
      featured: false,
      isUpcoming: true,
      downloads: 0
    },
    {
      id: "b_isa_10",
      titleAr: "النُّورُ المُسْتَبِينُ فِي مَعَالِمِ هَدْيِ الصَّادِقِ الأَمِينِ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ",
      titleHa: "An-Nurul Mustabin fi Ma'alimi Hadyis Sadiqil Amin Sallallahu Alaihi Wa Sallam",
      titleEn: "The Manifest Light: Key Milestones in the Guidance of the Prophet (PBUH)",
      authorAr: "إبراهيم شريف أبوبكر",
      authorHa: "Sheikh Ibrahim Sharif Abubakar",
      authorEn: "Sheikh Ibrahim Sharif Abubakar",
      category: "seerah",
      pages: 410,
      size: "قيد الإعداد",
      year: "1446H - قريباً",
      cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "#",
      descriptionAr: "رحلة ماتعة في السيرة النبوية العطرة، تبرز معالم الاقتداء برسول الله صلى الله عليه وسلم والدروس التربوية والدعوية للأمة.",
      descriptionHa: "Kyakkyawan littafin tarihin rayuwar Manzon Allah (SAW) da darussan koyi da halayensa na gari a fannin tarbiyya da rayuwa.",
      descriptionEn: "An illuminating prophetic biography focusing on practical emulation, moral character, and educational milestones.",
      featured: true,
      isUpcoming: true,
      downloads: 0
    },
    {
      id: "b_isa_11",
      titleAr: "شَمْسَا التَّجْدِيدِ فِي مَنَاقِبِ الإِمَامِ مُحَمَّدِ بْنِ عَبْدِ الوَهَّابِ وَحَفِيدِهِ مُحَمَّدِ بْنِ إِبْرَاهِيمَ إِمَامَيِ التَّوْحِيدِ",
      titleHa: "Shamsat Tajdidi fi Manaqibil Imami Muhammad bin Abdulwahhab wa Hafidihi Muhammad bin Ibrahim",
      titleEn: "The Two Suns of Renewal: Virtues and Biographies of Imam Muhammad bin Abdulwahhab and his Grandson Sheikh Muhammad bin Ibrahim",
      authorAr: "إبراهيم شريف أبوبكر",
      authorHa: "Sheikh Ibrahim Sharif Abubakar",
      authorEn: "Sheikh Ibrahim Sharif Abubakar",
      category: "fatawa",
      pages: 450,
      size: "قيد الإعداد",
      year: "1446H - قريباً",
      cover: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "#",
      descriptionAr: "كتاب تاريخي وسيري مؤصل يجمع تراجم ومناقب إمامي الدعوة السلفية: الشيخ المجدد محمد بن عبد الوهاب، وحفيده مفتي الديار السعودية الشيخ محمد بن إبراهيم آل الشيخ رحمهما الله.",
      descriptionHa: "Tarihi mai zurfi da bayyana darajar manyan malaman Sunnah guda biyu: Sheikh Muhammad bin Abdulwahhab da jikansa Sheikh Muhammad bin Ibrahim Aal Al-Sheikh.",
      descriptionEn: "A biographical and historical study chronicling the reformist legacies and scholarship of both legendary Imams of Tawheed.",
      featured: true,
      isUpcoming: true,
      downloads: 0
    },
    {
      id: "b_isa_12",
      titleAr: "إِبْرَازُ المَعَانِي فِي شَرْحِ عَقِيدَةِ الرَّازِيَّيْنِ عَلَمَيِ الزَّمَانِ",
      titleHa: "Ibrazul Ma'ani fi Sharhi Aqidatir Raziyyaini Alamayiz Zaman",
      titleEn: "Ibraz al-Ma'ani: Commentary on the Creed of the Two Razis (Abu Hatim & Abu Zur'ah)",
      authorAr: "إبراهيم شريف أبوبكر",
      authorHa: "Sheikh Ibrahim Sharif Abubakar",
      authorEn: "Sheikh Ibrahim Sharif Abubakar",
      category: "aqeedah",
      pages: 230,
      size: "قيد الإعداد",
      year: "1446H - قريباً",
      cover: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "#",
      descriptionAr: "شرح نفيس ومحرر لمتن أصل السنة واعتقاد الدين للإمامين الحافظين أبي حاتم الرازي وأبي زرعة الرازي رحمهما الله.",
      descriptionHa: "Sharhi mai zurfi kan littafin Usulus Sunnah da Aqidar Ahlus Sunnah na manyan malaman Hadisi guda biyu na garin Rayy (Abu Hatim da Abu Zur'ah).",
      descriptionEn: "A scholarly commentary on the foundational creed formulated and transmitted by the two leading hadith masters of Rayy.",
      featured: true,
      isUpcoming: true,
      downloads: 0
    },
    {
      id: "b_isa_13",
      titleAr: "ثِمَارُ التَّدَبُّرِ فِي لَطَائِفِ آيِ القُرْآنِ وَحِكَمِ العِبَرِ",
      titleHa: "Simarut Tadabburi fi Lata'ifi Ayil Qur'ani wa Hikamil Ibar",
      titleEn: "Fruits of Contemplation: Subtle Meanings and Wisdoms of Quranic Verses",
      authorAr: "إبراهيم شريف أبوبكر",
      authorHa: "Sheikh Ibrahim Sharif Abubakar",
      authorEn: "Sheikh Ibrahim Sharif Abubakar",
      category: "tafseer",
      pages: 360,
      size: "قيد الإعداد",
      year: "1446H - قريباً",
      cover: "https://images.unsplash.com/photo-1507842229451-7f01be7ff6ab?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "#",
      descriptionAr: "وقفات تدبرية عميقة تستخرج المعاني الإيمانية والإعجاز البياني والحكم التربوية من آيات الكتاب العزيز لإصلاح القلوب والواقع.",
      descriptionHa: "Bimbini mai zurfi kan ayoyin Alkur'ani wajen ciro hikimomi, mu'ujizozin lafazi, da darussan tarbiyya domin gyaran zukata da rayuwa.",
      descriptionEn: "Profound Quranic reflections extracting thematic pearls, linguistic miracles, and spiritual guidance for practical living.",
      featured: true,
      isUpcoming: true,
      downloads: 0
    },
    {
      id: "b_isa_14",
      titleAr: "مِعْرَاجُ البَيَانِ إِلَى مَعَالِمِ عُلُومِ القُرْآنِ",
      titleHa: "Mi'rajul Bayani ila Ma'alimi Ulumil Qur'an",
      titleEn: "Ascent of Clarification: Fundamentals of Quranic Sciences",
      authorAr: "إبراهيم شريف أبوبكر",
      authorHa: "Sheikh Ibrahim Sharif Abubakar",
      authorEn: "Sheikh Ibrahim Sharif Abubakar",
      category: "tafseer",
      pages: 310,
      size: "قيد الإعداد",
      year: "1446H - قريباً",
      cover: "https://images.unsplash.com/photo-1609599006353-e629aaabfeae?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "#",
      descriptionAr: "مصنف منهجي ميسر ومؤصل يجمع أهم مباحث علوم القرآن كأسباب النزول والمكي والمدني والناسخ والمنسوخ والإعجاز لطلاب العلم.",
      descriptionHa: "Kundi na musamman da ya tattara muhimman rassan ilimin Alkur'ani (Asbabun Nuzul, Makki da Madani, Nasikh da Mansukh, da I'jaz) ga daliban ilimi.",
      descriptionEn: "A systematic curriculum covering the essential disciplines of Quranic sciences with analytical precision.",
      featured: true,
      isUpcoming: true,
      downloads: 0
    },
    {
      id: "b_isa_15",
      titleAr: "نَيْلُ الأَمَانِي فِي شَرْحِ مَنْظُومَةِ البَيْقُونِيِّ لِكُلِّ طَالِبٍ وَعَانِي",
      titleHa: "Naylul Amani fi Sharhi Manzumatil Bayquniyyah",
      titleEn: "Nayl al-Amani: Commentary on the Bayquniyyah in Hadith Terminology",
      authorAr: "إبراهيم شريف أبوبكر",
      authorHa: "Sheikh Ibrahim Sharif Abubakar",
      authorEn: "Sheikh Ibrahim Sharif Abubakar",
      category: "hadith",
      pages: 69,
      size: "2.32 MB",
      year: "1448H",
      cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "pdf/2_nayl_al_amani.pdf",
      htmlUrl: "books_html/2_nayl_al_amani.html",
      descriptionAr: "شرح مبسط ومحرر لمنظومة البيقونية في مصطلح الحديث، ييسر فهم أنواع الحديث وضوابط الرواية والدراية لطلاب العلم.",
      descriptionHa: "Sharhi mai sauki da bayyani kan matanin Manzumar Al-Bayquniyyah a ilimin Mustalahul Hadisi domin fahimtar nau'o'in hadisai da ka'idojinsu.",
      descriptionEn: "An accessible commentary on the classic Bayquniyyah poem covering the foundations and classifications of Hadith terminology.",
      featured: true,
      isUpcoming: false,
      downloads: 1620
    },
    {
      id: "b_isa_16",
      titleAr: "مَنَارُ السَّعَادَةِ فِي حُقُوقِ الزَّوْجَيْنِ وَتَرْبِيَةِ الأَوْلَادِ عَلَى السُّنَّةِ وَالعِبَادَةِ",
      titleHa: "Manarus Sa'adah fi Huquqiz Zawjayni wa Tarbiyatil Awlad alas Sunnah wal Ibadah",
      titleEn: "The Beacon of Happiness: Marital Rights and Upbringing Children upon the Sunnah",
      authorAr: "إبراهيم شريف أبوبكر",
      authorHa: "Sheikh Ibrahim Sharif Abubakar",
      authorEn: "Sheikh Ibrahim Sharif Abubakar",
      category: "fiqh",
      pages: 270,
      size: "قيد الإعداد",
      year: "1446H - قريباً",
      cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "#",
      descriptionAr: "دليل تربوي وفقهي مؤصل في بيان واجبات وحقوق الزوجين وآداب المعاشرة، والمنهج النبوي الرشيد في تنشئة الأبناء وصلاح الأسرة المسلمة.",
      descriptionHa: "Littafi mai matukar mahimmanci a fannin zamantakewar aure, hakkokin ma'aurata, da tsarin Musulunci wajen tarbiyyantar da 'ya'ya a kan Sunnah.",
      descriptionEn: "A comprehensive guide on spousal rights, marital bliss, and the prophetic methodology in parenting and family cultivation.",
      featured: true,
      isUpcoming: true,
      downloads: 0
    },
    {
      id: "b_isa_17",
      titleAr: "مَسْلَكُ الأَبْرَارِ فِي عَمَلِ اليَوْمِ وَاللَّيْلَةِ وَمُوجِبَاتِ الأَجْرِ وَالأَذْكَارِ",
      titleHa: "Maslakul Abrar fi Amalil Yawmi wal Laylah wa Mujibatil Ajri wal Azkar",
      titleEn: "The Pathway of the Righteous: Daily and Nightly Prophetic Devotions and Invocations",
      authorAr: "إبراهيم شريف أبوبكر",
      authorHa: "Sheikh Ibrahim Sharif Abubakar",
      authorEn: "Sheikh Ibrahim Sharif Abubakar",
      category: "hadith",
      pages: 220,
      size: "قيد الإعداد",
      year: "1446H - قريباً",
      cover: "https://images.unsplash.com/photo-1532012164546-f432f2e3777a?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "#",
      descriptionAr: "كتاب مبارك يجمع وظائف اليوم والليلة من الاستيقاظ إلى النوم، والأذكار والأدعية الثابتة عن النبي صلى الله عليه وسلم لتحصين المسلم ونيل الأجور.",
      descriptionHa: "Littafi mai albarka da ya tattaro ayyuka da azkar na dare da rana da ingantattun addu'o'in Manzon Allah (SAW) domin neman lada da tsari.",
      descriptionEn: "A devotional compendium compiling authentic prophetic supplications, daily routines, and spiritual devotions from dawn to dusk.",
      featured: true,
      isUpcoming: true,
      downloads: 0
    },
    {
      id: "b_isa_18",
      titleAr: "المَنْهَلُ الصَّافِي فِي شَرْحِ قَوَاعِدِ السَّعْدِيِّ بِالبَيَانِ الشَّافِي",
      titleHa: "Al-Manhalus Safi fi Sharhi Qawa'idis Sa'di bil Bayanish Shafi",
      titleEn: "Al-Manhal al-Safi: A Comprehensive Commentary on Sheikh al-Sa'di's Legal Maxims",
      authorAr: "إبراهيم شريف أبوبكر",
      authorHa: "Sheikh Ibrahim Sharif Abubakar",
      authorEn: "Sheikh Ibrahim Sharif Abubakar",
      category: "fiqh",
      pages: 45,
      size: "1.60 MB",
      year: "1448H",
      cover: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "pdf/4_al_manhal_as_safi.pdf",
      htmlUrl: "books_html/4_al_manhal_as_safi.html",
      descriptionAr: "شرح نفيس ومحرر لمنظومة القواعد الفقهية للعلامة عبد الرحمن السعدي، يوضح أصول الفقه وقواعده الكلية ويربط الفروع بالأصول بالبيان الشافي لطلاب العلم.",
      descriptionHa: "Sharhi mai albarka kuma mai sauki kan wakar Ka'idojin Fiqhu ta Sheikh Abdurrahman as-Sa'di, mai fayyace manyan ka'idojin Shari'a da gina rassan fiqhu a kansu da hujjoji.",
      descriptionEn: "A rich and lucid commentary on Sheikh Abdurrahman al-Sa'di's didactic poem on legal maxims, systematically elucidating universal principles and practical applications.",
      featured: true,
      isUpcoming: false,
      downloads: 1540
    },
    {
      id: "b_isa_19",
      titleAr: "عُمْدَةُ المُوَحِّدِ السَّدِيدِ فِي شَرْحِ حَقِّ اللهِ عَلَى العَبِيدِ",
      titleHa: "Umdatul Muwahhidis Sadidi fi Sharhi Haqqillahi alal Abid (Sharhin Kitabut Tauhid)",
      titleEn: "Umdat al-Muwahhid: Commentary on Allah's Right Over His Servants (Kitab at-Tawheed)",
      authorAr: "إبراهيم شريف أبوبكر",
      authorHa: "Sheikh Ibrahim Sharif Abubakar",
      authorEn: "Sheikh Ibrahim Sharif Abubakar",
      category: "aqeedah",
      pages: 184,
      size: "3.43 MB",
      year: "1448H",
      cover: "https://images.unsplash.com/photo-1532012164546-f432f2e3777a?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "pdf/5_umdat_al_muwahhid.pdf",
      htmlUrl: "books_html/5_umdat_al_muwahhid.html",
      descriptionAr: "شرح تحليلي ومنهجي محرر لكتاب التوحيد للإمام المجدد محمد بن عبد الوهاب، يبرز مقاصد الأبواب ويقرر دلائل التوحيد ويهدم شبهات الشرك بالأدلة الواضحة.",
      descriptionHa: "Sharhi ne mai zurfi da bayyani dalla-dalla kan babbar manhajar Kitabut Tauhid ta Sheikhul Islam Muhammad bin Abdulwahhab, mai fayyace ma'anonin babobi da hujjojin Tauhidi.",
      descriptionEn: "A profound, systematic commentary on Imam Muhammad bin Abdulwahhab's Kitab at-Tawheed, explaining chapter objectives and Monotheistic proofs.",
      featured: true,
      isUpcoming: false,
      downloads: 2150
    },

    // --- Classical Reference Books of the Markaz Library ---
    {
      id: "b1",
      titleAr: "مجموع فتاوى ورسائل سماحة الشيخ محمد بن إبراهيم آل الشيخ",
      titleHa: "Majmu'u Fatawa da Wasikun Sheikh Muhammad bin Ibrahim (Kundin Fatawoyi)",
      titleEn: "Collected Fatawa and Treatises of Sheikh Muhammad bin Ibrahim",
      authorAr: "الشيخ محمد بن إبراهيم آل الشيخ",
      authorHa: "Sheikh Muhammad bin Ibrahim Aal Al-Sheikh",
      authorEn: "Sheikh Muhammad bin Ibrahim Aal Al-Sheikh",
      category: "fatawa",
      pages: 420,
      size: "14.2 MB",
      year: "1399H",
      cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      descriptionAr: "الموسوعة الفقهية الكبرى التي جمعت فتاوى سماحة الشيخ ورسائله العلمية وأحكامه في مختلف الأبواب الشرعية.",
      descriptionHa: "Babban kundin fatawoyi da rubuce-rubucen Sheikh Muhammad bin Ibrahim wanda ya kunshi amsoshin tambayoyi da hukunce-hukunce a fannoni daban-daban.",
      descriptionEn: "The comprehensive collection of legal verdicts and scholarly letters of Grand Mufti Sheikh Muhammad bin Ibrahim.",
      featured: true,
      downloads: 1420
    },
    {
      id: "b2",
      titleAr: "شرح كشف الشبهات",
      titleHa: "Sharhin Littafin Kashfus Shubuhat",
      titleEn: "Explanation of Kashf al-Shubuhat (Removal of Doubts)",
      authorAr: "الشيخ محمد بن إبراهيم آل الشيخ",
      authorHa: "Sheikh Muhammad bin Ibrahim Aal Al-Sheikh",
      authorEn: "Sheikh Muhammad bin Ibrahim Aal Al-Sheikh",
      category: "aqeedah",
      pages: 180,
      size: "5.8 MB",
      year: "1405H",
      cover: "https://images.unsplash.com/photo-1532012164546-f432f2e3777a?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      descriptionAr: "شرح نفيس ومؤصل لكتاب كشف الشبهات في بيان حقيقة التوحيد ودحض شبهات المشركين بأدلة القرآن والسنة.",
      descriptionHa: "Kyakkyawan sharhi mai zurfi kan littafin Kashfus Shubuhat wajen bayyana hakikanin Tauhidi da warware shubuhohin masu shirka da hujjojin Alkur'ani da Sunnah.",
      descriptionEn: "A profound explanation clarifying the pure Tawheed and refuting misconceptions with solid evidences.",
      featured: true,
      downloads: 980
    },
    {
      id: "b3",
      titleAr: "الأصول الثلاثة وأدلتها",
      titleHa: "Littafin Usulus Salasa da Hujjojinsa",
      titleEn: "The Three Fundamental Principles",
      authorAr: "الإمام محمد بن عبد الوهاب",
      authorHa: "Imam Muhammad bin Abdulwahhab",
      authorEn: "Imam Muhammad bin Abdulwahhab",
      category: "aqeedah",
      pages: 64,
      size: "2.1 MB",
      year: "1206H",
      cover: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      descriptionAr: "متن عقدي تأسيسي في معرفة العبد ربه، ودينه، ونبيه محمداً صلى الله عليه وسلم بالأدلة.",
      descriptionHa: "Tushen littafin da ya wajaba kowane Musulmi ya sani: Sanin Ubangiji, Sanin Addinin Musulunci, da Sanin Annabi Muhammad (SAW).",
      descriptionEn: "A foundational text on the three principles every Muslim must know: Knowing Allah, Islam, and the Prophet Muhammad (PBUH).",
      featured: true,
      downloads: 2350
    },
    {
      id: "b4",
      titleAr: "عمدة الأحكام من كلام خير الأنام",
      titleHa: "Littafin Umdatul Ahkam (Hadisan Hukunce-Hukunce)",
      titleEn: "Umdat al-Ahkam (Pillars of Rulings)",
      authorAr: "الإمام عبد الغني المقدسي",
      authorHa: "Imam Abdul-Ghaniy al-Maqdisi",
      authorEn: "Imam Abdul-Ghani al-Maqdisi",
      category: "hadith",
      pages: 260,
      size: "7.4 MB",
      year: "600H",
      cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      descriptionAr: "كتاب جامع لأصح الأحاديث في الأحكام الفقهية المتفق عليها بين البخاري ومسلم.",
      descriptionHa: "Littafi mai tattare da ingantattun hadisan hukunce-hukunce da Bukhari da Muslim suka hadu a kansu.",
      descriptionEn: "A collection of the most authentic Hadiths pertaining to Islamic legal rulings from Sahih Bukhari and Muslim.",
      featured: false,
      downloads: 870
    },
    {
      id: "b5",
      titleAr: "زاد المستقنع في اختصار المقنع",
      titleHa: "Zadul Mustaqni' (Littafin Fiqhun Hanbali)",
      titleEn: "Zad al-Mustaqni' in Fiqh",
      authorAr: "الإمام شرف الدين موسى الحجاوي",
      authorHa: "Imam Sharafuddin Musa al-Hajjawi",
      authorEn: "Imam Sharaf al-Din Musa al-Hajjawi",
      category: "fiqh",
      pages: 310,
      size: "8.9 MB",
      year: "968H",
      cover: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      descriptionAr: "عمدة المتفقهين في الفقه المقارن والمذهب، اعتنى به أئمة العلم والتحقيق شرحاً وحفظاً.",
      descriptionHa: "Daya daga cikin manyan litattafan fiqhu da ake karantarwa a markazai da jami'o'in Musulunci.",
      descriptionEn: "A core classical manual of jurisprudence widely studied and explained by scholars.",
      featured: false,
      downloads: 650
    },
    {
      id: "b6",
      titleAr: "تفسير السعدي (تيسير الكريم الرحمن)",
      titleHa: "Tafsirin Sheikh Sa'adi (Taysirul Kareemir Rahman)",
      titleEn: "Tafsir al-Sa'di (Taysir al-Karim al-Rahman)",
      authorAr: "الشيخ عبد الرحمن بن ناصر السعدي",
      authorHa: "Sheikh Abdurrahman bin Nasir as-Sa'di",
      authorEn: "Sheikh Abd al-Rahman al-Sa'di",
      category: "tafseer",
      pages: 980,
      size: "24.5 MB",
      year: "1376H",
      cover: "https://images.unsplash.com/photo-1609599006353-e629aaabfeae?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      descriptionAr: "تفسير ميسر وسهل العبارة وواضح المعاني، معتنٍ ببيان مقاصد الآيات والدروس المستفادة.",
      descriptionHa: "Tafsirin Alkur'ani mai saukin fahimta, mai bayyana ma'anoni da darussan da ke cikin ayoyi a sarari.",
      descriptionEn: "A renowned, accessible Tafsir explaining the verses of the Holy Quran with clarity and spiritual depth.",
      featured: true,
      downloads: 3100
    },
    {
      id: "b7",
      titleAr: "الرحيق المختوم في سيرة النبي الأمين",
      titleHa: "Ar-Raheequl Makhtum (Kyakkyawar Tarihin Annabi SAW)",
      titleEn: "The Sealed Nectar (Ar-Raheeq Al-Makhtum)",
      authorAr: "الشيخ صفي الرحمن المباركفوري",
      authorHa: "Sheikh Safiyur-Rahman al-Mubarakfuri",
      authorEn: "Sheikh Safiur Rahman al-Mubarakpuri",
      category: "seerah",
      pages: 520,
      size: "12.8 MB",
      year: "1427H",
      cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      descriptionAr: "الكتاب الحائز على الجائزة الأولى في مسابقة رابطة العالم الإسلامي للسيرة النبوية الشريفة.",
      descriptionHa: "Littafin da ya lashe lambar yabo ta farko a duniya wajen bayyana tarihin Annabi Muhammad (SAW) dalla-dalla.",
      descriptionEn: "Award-winning authoritative biography of the Noble Prophet Muhammad (Peace Be Upon Him).",
      featured: true,
      downloads: 1890
    },
    {
      id: "b8",
      titleAr: "الآجرومية في علم قواعد العربية",
      titleHa: "Matanin Al-Ajrumiyyah a Nahawun Larabci",
      titleEn: "Al-Ajrumiyyah in Arabic Grammar",
      authorAr: "ابن آجروم الصنهاجي",
      authorHa: "Ibn Ajrum as-Sanhaji",
      authorEn: "Ibn Ajurrum",
      category: "arabic",
      pages: 48,
      size: "1.5 MB",
      year: "723H",
      cover: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      descriptionAr: "مقدمة مباركة وموجزة في مبادئ علم النحو، مفتاح فهم لغة التنزيل والحديث النبوي.",
      descriptionHa: "Mabuɗin koyon ilimin Nahawu da ka'idojin harshen Larabci domin fahimtar Alkur'ani da Hadisi.",
      descriptionEn: "The essential foundational primer on Arabic grammar and syntax.",
      featured: false,
      downloads: 1120
    }
  ],

  audios: [
    {
      id: "a_tuhfa_001",
      titleAr: "شرح كتاب تحفة الولدان من أحاديث النبي صلى الله عليه وسلم عن القرآن - المجلس الأول",
      titleHa: "Sharhin Tuhfatul Wildan (Hadisan Annabi SAW kan Alkur'ani) - Zama na 01",
      titleEn: "Explanation of Tuhfat al-Wildan - Lesson 01",
      speakerAr: "إبراهيم شريف أبوبكر",
      speakerHa: "Sheikh Ibrahim Sharif Abubakar",
      speakerEn: "Sheikh Ibrahim Sharif Abubakar",
      category: "hadith",
      duration: "34:20",
      audioUrl: "https://actions.google.com/sounds/v1/ambiences/daytime_forest_bonfire.ogg",
      date: "1446/03/15",
      fileSize: "16 MB",
      featured: true
    },
    {
      id: "a_alfu_001",
      titleAr: "شرح كتاب ألف حديث وحديث من صحيح سنن خير البرية - المجلس الأول (المقدمة)",
      titleHa: "Sharhin Alfu Hadithin Wa Hadith (Hadisi 1001) - Zama na 01 (Mukaddima)",
      titleEn: "Explanation of 1001 Hadiths - Lesson 01 (Introduction)",
      speakerAr: "إبراهيم شريف أبوبكر",
      speakerHa: "Sheikh Ibrahim Sharif Abubakar",
      speakerEn: "Sheikh Ibrahim Sharif Abubakar",
      category: "hadith",
      duration: "42:10",
      audioUrl: "https://actions.google.com/sounds/v1/ambiences/daytime_forest_bonfire.ogg",
      date: "1446/03/10",
      fileSize: "20 MB",
      featured: true
    },
    {
      id: "a1",
      titleAr: "شرح كتاب التوحيد - الدرس الأول (مقدمة في معنى التوحيد)",
      titleHa: "Sharhin Kitabut Tauhid - Darasi na 01 (Fassarar Tauhidi)",
      titleEn: "Explanation of Kitab at-Tawheed - Lesson 01",
      speakerAr: "فضيلة الشيخ الدكتور / أستاذ المركز",
      speakerHa: "Malamin Markazi / Dr. Malam",
      speakerEn: "Center Sheikh / Lecturer",
      category: "aqeedah",
      duration: "45:20",
      audioUrl: "https://actions.google.com/sounds/v1/ambiences/daytime_forest_bonfire.ogg",
      date: "1446/02/10",
      fileSize: "21 MB",
      featured: false
    },
    {
      id: "a4",
      titleAr: "وقفات مع سيرة الشيخ محمد بن إبراهيم آل الشيخ رحمه الله",
      titleHa: "Bitar Tarihin Rayuwar Sheikh Muhammad bin Ibrahim Aal Al-Sheikh",
      titleEn: "Biography & Milestones of Sheikh Muhammad bin Ibrahim",
      speakerAr: "مدير المركز والمشرف العام",
      speakerHa: "Babban Daraktan Markazi",
      speakerEn: "General Supervisor of the Markaz",
      category: "fatawa",
      duration: "61:10",
      audioUrl: "https://actions.google.com/sounds/v1/ambiences/daytime_forest_bonfire.ogg",
      date: "1446/01/01",
      fileSize: "29 MB",
      featured: true
    }
  ],

  videos: [
    {
      id: "v1",
      titleAr: "حفل افتتاح مركز محمد بن إبراهيم آل الشيخ رحمه الله وتدشين البرامج",
      titleHa: "Bikin Bude Cibiyar Sheikh Muhammad bin Ibrahim da Kaddamar da Karatuttuka",
      titleEn: "Inauguration Ceremony & Launching of Markaz Programs",
      instructorAr: "إدارة المركز ولفيف من العلماء",
      instructorHa: "Shugabannin Markazi da Manyan Malamai",
      instructorEn: "Center Board & Scholars",
      duration: "1:15:30",
      thumbnail: "https://images.unsplash.com/photo-1590076215667-875d4ef2d7ee?auto=format&fit=crop&w=800&q=80",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      category: "lessons",
      date: "1446/01/15",
      views: 3420,
      featured: true
    },
    {
      id: "v2",
      titleAr: "دورة مكثفة في العقيدة السلفية - المحاضرة الأولى",
      titleHa: "Kwas na Musamman kan Aqeedar Salaf - Zama na 01",
      titleEn: "Intensive Creed Course - Lecture 01",
      instructorAr: "فضيلة الشيخ المدرس بالمركز",
      instructorHa: "Malami mai Karantarwa a Markazi",
      instructorEn: "Resident Scholar",
      duration: "55:12",
      thumbnail: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      category: "aqeedah",
      date: "1446/02/01",
      views: 1850,
      featured: true
    }
  ],

  schedule: [
    {
      id: "s_sat",
      dayAr: "السبت",
      dayHa: "Asabar (Saturday)",
      dayEn: "Saturday",
      time: "Daren Asabar / Lokacin Karatu",
      subjectAr: "شرح كتاب: ألف حديث وحديث من صحيح سنن خير البرية",
      subjectHa: "Sharhin Littafin: Alfu Hadithin Wa Hadith (1001 Hadisai)",
      subjectEn: "Explanation of 1001 Hadiths from Sahih Sunnah",
      teacherAr: "إبراهيم شريف أبوبكر",
      teacherHa: "Sheikh Ibrahim Sharif Abubakar",
      teacherEn: "Sheikh Ibrahim Sharif Abubakar",
      locationAr: "دائرة دروس المركز ومجموعة الواتساب الرسمية",
      locationHa: "Dandalin Karatu na Markaz & WhatsApp Group",
      locationEn: "Markaz Center & Official WhatsApp Group"
    },
    {
      id: "s_mon",
      dayAr: "الإثنين",
      dayHa: "Litinin (Monday)",
      dayEn: "Monday",
      time: "Daren Litinin / Lokacin Karatu",
      subjectAr: "شرح كتاب: تحفة الولدان من أحاديث النبي صلى الله عليه وسلم عن القرآن",
      subjectHa: "Sharhin Littafin: Tuhfatul Wildan (Hadisan Falalar Alkur'ani)",
      subjectEn: "Explanation of Tuhfat al-Wildan on Quran Virtues",
      teacherAr: "إبراهيم شريف أبوبكر",
      teacherHa: "Sheikh Ibrahim Sharif Abubakar",
      teacherEn: "Sheikh Ibrahim Sharif Abubakar",
      locationAr: "دائرة دروس المركز ومجموعة الواتساب الرسمية",
      locationHa: "Dandalin Karatu na Markaz & WhatsApp Group",
      locationEn: "Markaz Center & Official WhatsApp Group"
    },
    {
      id: "s_thu",
      dayAr: "الخميس",
      dayHa: "Alhamis (Thursday)",
      dayEn: "Thursday",
      time: "Daren Alhamis / Lokacin Karatu",
      subjectAr: "شرح كتاب: ألف حديث وحديث من صحيح سنن خير البرية",
      subjectHa: "Sharhin Littafin: Alfu Hadithin Wa Hadith (1001 Hadisai)",
      subjectEn: "Explanation of 1001 Hadiths from Sahih Sunnah",
      teacherAr: "إبراهيم شريف أبوبكر",
      teacherHa: "Sheikh Ibrahim Sharif Abubakar",
      teacherEn: "Sheikh Ibrahim Sharif Abubakar",
      locationAr: "دائرة دروس المركز ومجموعة الواتساب الرسمية",
      locationHa: "Dandalin Karatu na Markaz & WhatsApp Group",
      locationEn: "Markaz Center & Official WhatsApp Group"
    }
  ]
};

if (typeof window !== "undefined") {
  window.MARKAZ_DATA = INITIAL_DATA;
}
