/**
 * Taskar Bayanai na Markazi (Markaz Knowledge Database)
 * مركز محمد بن إبراهيم آل الشيخ رحمه الله
 */

const INITIAL_DATA = {
  markazInfo: {
    nameAr: "مركز محمد بن إبراهيم آل الشيخ رحمه الله للعلوم الشرعية",
    nameHa: "Cibiyar Sheikh Muhammad bin Ibrahim Aal Al-Sheikh Domin Ilimin Addinin Musulunci",
    nameEn: "Sheikh Muhammad bin Ibrahim Aal Al-Sheikh Islamic Center",
    taglineAr: "منارة لنشر العلم الشرعي المؤصل على منهج الكتاب والسنة",
    taglineHa: "Hasken yada ingantaccen ilimin addinin Musulunci bisa koyarwar Alkur'ani da Sunnah",
    taglineEn: "A beacon for authentic Islamic knowledge based on the Quran and Sunnah",
    location: "Kano / Nigeria",
    contactEmail: "info@markaz-alsheikh.org",
    contactPhone: "+234 800 000 0000",
    establishedYear: 1446
  },

  categories: [
    { id: "all", nameAr: "جميع الأقسام", nameHa: "Dukkan Bangarori", nameEn: "All Categories", icon: "📚" },
    { id: "aqeedah", nameAr: "العقيدة والتوحيد", nameHa: "Aqeedah & Tauhidi", nameEn: "Creed & Tawheed", icon: "🧭" },
    { id: "fiqh", nameAr: "الفقه وأصوله", nameHa: "Fiqhu & Usulinsa", nameEn: "Jurisprudence & Principles", icon: "⚖️" },
    { id: "hadith", nameAr: "الحديث وعلومه", nameHa: "Hadisi & Iliminsa", nameEn: "Hadith & Its Sciences", icon: "📜" },
    { id: "tafseer", nameAr: "التفسير وعلوم القرآن", nameHa: "Tafseeri & Alkur'ani", nameEn: "Tafsir & Quran Sciences", icon: "📖" },
    { id: "seerah", nameAr: "السيرة النبوية والتاريخ", nameHa: "Seerah & Tarihi", nameEn: "Prophetic Biography & History", icon: "🕌" },
    { id: "fatawa", nameAr: "فتاوى ورسائل الشيخ", nameHa: "Fatawoyin Sheikh Muhammad", nameEn: "Fatawa & Treatises of Sheikh", icon: "🖋️" },
    { id: "arabic", nameAr: "اللغة العربية والآداب", nameHa: "Harshen Larabci & Adabi", nameEn: "Arabic Language & Grammar", icon: "🔤" },
    { id: "lessons", nameAr: "دروس ودورات المركز", nameHa: "Darussan Cibiyar (Markaz)", nameEn: "Center Lessons & Courses", icon: "🎓" }
  ],

  books: [
    {
      id: "b1",
      titleAr: "مجموع فتاوى ورسائل سماحة الشيخ محمد بن إبراهيم آل الشيخ",
      titleHa: "Majmu'u Fatawa da Wasikun Sheikh Muhammad bin Ibrahim (Kundin Fatawoyi)",
      titleEn: "Collected Fatawa and Treatises of Sheikh Muhammad bin Ibrahim",
      authorAr: "الشيخ محمد بن إبراهيم آل الشيخ",
      authorHa: "Sheikh Muhammad bin Ibrahim Aal Al-Sheikh",
      authorEn: "Sheikh Muhammad bin Ibrahim Aal Al-Sheikh",
      category: "fatawa",
      pages: 420,
      size: "14.2 MB",
      year: "1399H",
      cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      descriptionAr: "الموسوعة الفقهية الكبرى التي جمعت فتاوى سماحة الشيخ ورسائله العلمية وأحكامه في مختلف الأبواب الشرعية.",
      descriptionHa: "Babban kundin fatawoyi da rubuce-rubucen Sheikh Muhammad bin Ibrahim wanda ya kunshi amsoshin tambayoyi da hukunce-hukunce a fannoni daban-daban.",
      descriptionEn: "The comprehensive collection of legal verdicts and scholarly letters of Grand Mufti Sheikh Muhammad bin Ibrahim.",
      featured: true,
      downloads: 1420
    },
    {
      id: "b2",
      titleAr: "شرح كشف الشبهات",
      titleHa: "Sharhin Littafin Kashfus Shubuhat",
      titleEn: "Explanation of Kashf al-Shubuhat (Removal of Doubts)",
      authorAr: "الشيخ محمد بن إبراهيم آل الشيخ",
      authorHa: "Sheikh Muhammad bin Ibrahim Aal Al-Sheikh",
      authorEn: "Sheikh Muhammad bin Ibrahim Aal Al-Sheikh",
      category: "aqeedah",
      pages: 180,
      size: "5.8 MB",
      year: "1405H",
      cover: "https://images.unsplash.com/photo-1532012164546-f432f2e3777a?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      descriptionAr: "شرح نفيس ومؤصل لكتاب كشف الشبهات في بيان حقيقة التوحيد ودحض شبهات المشركين بأدلة القرآن والسنة.",
      descriptionHa: "Kyakkyawan sharhi mai zurfi kan littafin Kashfus Shubuhat wajen bayyana hakikanin Tauhidi da warware shubuhohin masu shirka da hujjojin Alkur'ani da Sunnah.",
      descriptionEn: "A profound explanation clarifying the pure Tawheed and refuting misconceptions with solid evidences.",
      featured: true,
      downloads: 980
    },
    {
      id: "b3",
      titleAr: "الأصول الثلاثة وأدلتها",
      titleHa: "Littafin Usulus Salasa da Hujjojinsa",
      titleEn: "The Three Fundamental Principles",
      authorAr: "الإمام محمد بن عبد الوهاب",
      authorHa: "Imam Muhammad bin Abdulwahhab",
      authorEn: "Imam Muhammad bin Abdulwahhab",
      category: "aqeedah",
      pages: 64,
      size: "2.1 MB",
      year: "1206H",
      cover: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      descriptionAr: "متن عقدي تأسيسي في معرفة العبد ربه، ودينه، ونبيه محمداً صلى الله عليه وسلم بالأدلة.",
      descriptionHa: "Tushen littafin da ya wajaba kowane Musulmi ya sani: Sanin Ubangiji, Sanin Addinin Musulunci, da Sanin Annabi Muhammad (SAW).",
      descriptionEn: "A foundational text on the three principles every Muslim must know: Knowing Allah, Islam, and the Prophet Muhammad (PBUH).",
      featured: true,
      downloads: 2350
    },
    {
      id: "b4",
      titleAr: "عمدة الأحكام من كلام خير الأنام",
      titleHa: "Littafin Umdatul Ahkam (Hadisan Hukunce-Hukunce)",
      titleEn: "Umdat al-Ahkam (Pillars of Rulings)",
      authorAr: "الإمام عبد الغني المقدسي",
      authorHa: "Imam Abdul-Ghaniy al-Maqdisi",
      authorEn: "Imam Abdul-Ghani al-Maqdisi",
      category: "hadith",
      pages: 260,
      size: "7.4 MB",
      year: "600H",
      cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      descriptionAr: "كتاب جامع لأصح الأحاديث في الأحكام الفقهية المتفق عليها بين البخاري ومسلم.",
      descriptionHa: "Littafi mai tattare da ingantattun hadisan hukunce-hukunce da Bukhari da Muslim suka hadu a kansu.",
      descriptionEn: "A collection of the most authentic Hadiths pertaining to Islamic legal rulings from Sahih Bukhari and Muslim.",
      featured: false,
      downloads: 870
    },
    {
      id: "b5",
      titleAr: "زاد المستقنع في اختصار المقنع",
      titleHa: "Zadul Mustaqni' (Littafin Fiqhun Hanbali)",
      titleEn: "Zad al-Mustaqni' in Fiqh",
      authorAr: "الإمام شرف الدين موسى الحجاوي",
      authorHa: "Imam Sharafuddin Musa al-Hajjawi",
      authorEn: "Imam Sharaf al-Din Musa al-Hajjawi",
      category: "fiqh",
      pages: 310,
      size: "8.9 MB",
      year: "968H",
      cover: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      descriptionAr: "عمدة المتفقهين في الفقه المقارن والمذهب، اعتنى به أئمة العلم والتحقيق شرحاً وحفظاً.",
      descriptionHa: "Daya daga cikin manyan litattafan fiqhu da ake karantarwa a markazai da jami'o'in Musulunci.",
      descriptionEn: "A core classical manual of jurisprudence widely studied and explained by scholars.",
      featured: false,
      downloads: 650
    },
    {
      id: "b6",
      titleAr: "تفسير السعدي (تيسير الكريم الرحمن)",
      titleHa: "Tafsirin Sheikh Sa'adi (Taysirul Kareemir Rahman)",
      titleEn: "Tafsir al-Sa'di (Taysir al-Karim al-Rahman)",
      authorAr: "الشيخ عبد الرحمن بن ناصر السعدي",
      authorHa: "Sheikh Abdurrahman bin Nasir as-Sa'di",
      authorEn: "Sheikh Abd al-Rahman al-Sa'di",
      category: "tafseer",
      pages: 980,
      size: "24.5 MB",
      year: "1376H",
      cover: "https://images.unsplash.com/photo-1609599006353-e629aaabfeae?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      descriptionAr: "تفسير ميسر وسهل العبارة وواضح المعاني، معتنٍ ببيان مقاصد الآيات والدروس المستفادة.",
      descriptionHa: "Tafsirin Alkur'ani mai saukin fahimta, mai bayyana ma'anoni da darussan da ke cikin ayoyi a sarari.",
      descriptionEn: "A renowned, accessible Tafsir explaining the verses of the Holy Quran with clarity and spiritual depth.",
      featured: true,
      downloads: 3100
    },
    {
      id: "b7",
      titleAr: "الرحيق المختوم في سيرة النبي الأمين",
      titleHa: "Ar-Raheequl Makhtum (Kyakkyawar Tarihin Annabi SAW)",
      titleEn: "The Sealed Nectar (Ar-Raheeq Al-Makhtum)",
      authorAr: "الشيخ صفي الرحمن المباركفوري",
      authorHa: "Sheikh Safiyur-Rahman al-Mubarakfuri",
      authorEn: "Sheikh Safiur Rahman al-Mubarakpuri",
      category: "seerah",
      pages: 520,
      size: "12.8 MB",
      year: "1427H",
      cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      descriptionAr: "الكتاب الحائز على الجائزة الأولى في مسابقة رابطة العالم الإسلامي للسيرة النبوية الشريفة.",
      descriptionHa: "Littafin da ya lashe lambar yabo ta farko a duniya wajen bayyana tarihin Annabi Muhammad (SAW) dalla-dalla.",
      descriptionEn: "Award-winning authoritative biography of the Noble Prophet Muhammad (Peace Be Upon Him).",
      featured: true,
      downloads: 1890
    },
    {
      id: "b8",
      titleAr: "الآجرومية في علم قواعد العربية",
      titleHa: "Matanin Al-Ajrumiyyah a Nahawun Larabci",
      titleEn: "Al-Ajrumiyyah in Arabic Grammar",
      authorAr: "ابن آجروم الصنهاجي",
      authorHa: "Ibn Ajrum as-Sanhaji",
      authorEn: "Ibn Ajurrum",
      category: "arabic",
      pages: 48,
      size: "1.5 MB",
      year: "723H",
      cover: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=600&q=80",
      pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      descriptionAr: "مقدمة مباركة وموجزة في مبادئ علم النحو، مفتاح فهم لغة التنزيل والحديث النبوي.",
      descriptionHa: "Mabuɗin koyon ilimin Nahawu da ka'idojin harshen Larabci domin fahimtar Alkur'ani da Hadisi.",
      descriptionEn: "The essential foundational primer on Arabic grammar and syntax.",
      featured: false,
      downloads: 1120
    }
  ],

  audios: [
    {
      id: "a1",
      titleAr: "شرح كتاب التوحيد - الدرس الأول (مقدمة في معنى التوحيد)",
      titleHa: "Sharhin Kitabut Tauhid - Darasi na 01 (Fassarar Tauhidi)",
      titleEn: "Explanation of Kitab at-Tawheed - Lesson 01",
      speakerAr: "فضيلة الشيخ الدكتور / أستاذ المركز",
      speakerHa: "Malamin Markazi / Dr. Malam",
      speakerEn: "Center Sheikh / Lecturer",
      category: "aqeedah",
      duration: "45:20",
      audioUrl: "https://actions.google.com/sounds/v1/ambiences/daytime_forest_bonfire.ogg",
      date: "1446/02/10",
      fileSize: "21 MB",
      featured: true
    },
    {
      id: "a2",
      titleAr: "شرح الأصول الثلاثة - الدرس الأول",
      titleHa: "Sharhin Usulus Salasa - Darasi na 01 (Kashin Farko)",
      titleEn: "Explanation of the Three Principles - Lesson 01",
      speakerAr: "أستاذ كرسي العقيدة بالمركز",
      speakerHa: "Babban Malamin Aqeedah na Markazi",
      speakerEn: "Center Faculty Sheikh",
      category: "aqeedah",
      duration: "38:15",
      audioUrl: "https://actions.google.com/sounds/v1/ambiences/daytime_forest_bonfire.ogg",
      date: "1446/02/12",
      fileSize: "18 MB",
      featured: true
    },
    {
      id: "a3",
      titleAr: "شرح عمدة الأحكام - كتاب الطهارة (الحديث الأول والثاني)",
      titleHa: "Sharhin Umdatul Ahkam - Babin Tsarki (Hadisi na 1 & 2)",
      titleEn: "Umdat al-Ahkam - Book of Purification (Hadith 1-2)",
      speakerAr: "مدرس الحديث والفقه بالمركز",
      speakerHa: "Malamin Hadisi da Fiqhu na Markazi",
      speakerEn: "Hadith & Fiqh Scholar",
      category: "hadith",
      duration: "52:40",
      audioUrl: "https://actions.google.com/sounds/v1/ambiences/daytime_forest_bonfire.ogg",
      date: "1446/02/15",
      fileSize: "25 MB",
      featured: false
    },
    {
      id: "a4",
      titleAr: "وقفات مع سيرة الشيخ محمد بن إبراهيم آل الشيخ رحمه الله",
      titleHa: "Bitar Tarihin Rayuwar Sheikh Muhammad bin Ibrahim Aal Al-Sheikh",
      titleEn: "Biography & Milestones of Sheikh Muhammad bin Ibrahim",
      speakerAr: "مدير المركز والمشرف العام",
      speakerHa: "Babban Daraktan Markazi",
      speakerEn: "General Supervisor of the Markaz",
      category: "fatawa",
      duration: "61:10",
      audioUrl: "https://actions.google.com/sounds/v1/ambiences/daytime_forest_bonfire.ogg",
      date: "1446/01/01",
      fileSize: "29 MB",
      featured: true
    },
    {
      id: "a5",
      titleAr: "دروس التفسير - سورة الفاتحة وأوائل سورة البقرة",
      titleHa: "Darussan Tafseer - Suratul Fatiha da Fara Suratul Baqarah",
      titleEn: "Quran Tafsir - Surah Al-Fatihah & Al-Baqarah",
      speakerAr: "أستاذ علوم القرآن والتفسير",
      speakerHa: "Malamin Tafseer na Markazi",
      speakerEn: "Quranic Sciences Scholar",
      category: "tafseer",
      duration: "48:50",
      audioUrl: "https://actions.google.com/sounds/v1/ambiences/daytime_forest_bonfire.ogg",
      date: "1446/02/18",
      fileSize: "23 MB",
      featured: false
    }
  ],

  videos: [
    {
      id: "v1",
      titleAr: "حفل افتتاح مركز محمد بن إبراهيم آل الشيخ رحمه الله وتدشين البرامج",
      titleHa: "Bikin Bude Cibiyar Sheikh Muhammad bin Ibrahim da Kaddamar da Karatuttuka",
      titleEn: "Inauguration Ceremony & Launching of Markaz Programs",
      instructorAr: "إدارة المركز ولفيف من العلماء",
      instructorHa: "Shugabannin Markazi da Manyan Malamai",
      instructorEn: "Center Board & Scholars",
      duration: "1:15:30",
      thumbnail: "https://images.unsplash.com/photo-1590076215667-875d4ef2d7ee?auto=format&fit=crop&w=800&q=80",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      category: "lessons",
      date: "1446/01/15",
      views: 3420,
      featured: true
    },
    {
      id: "v2",
      titleAr: "دورة مكثفة في العقيدة السلفية - المحاضرة الأولى",
      titleHa: "Kwas na Musamman kan Aqeedar Salaf - Zama na 01",
      titleEn: "Intensive Creed Course - Lecture 01",
      instructorAr: "فضيلة الشيخ المدرس بالمركز",
      instructorHa: "Malami mai Karantarwa a Markazi",
      instructorEn: "Resident Scholar",
      duration: "55:12",
      thumbnail: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      category: "aqeedah",
      date: "1446/02/01",
      views: 1850,
      featured: true
    },
    {
      id: "v3",
      titleAr: "طريقة طلب العلم الشرعي والتدرج في المتون للشيخ محمد بن إبراهيم",
      titleHa: "Hanyoyin Neman Ilimi da Tsarin Karanta Matani na Addini",
      titleEn: "Methodology of Seeking Islamic Knowledge & Texts",
      instructorAr: "المشرف العلمي للمركز",
      instructorHa: "Shugaban Sashen Ilimi na Markazi",
      instructorEn: "Academic Supervisor",
      duration: "42:00",
      thumbnail: "https://images.unsplash.com/photo-1584697964190-7bb9d5f7f98c?auto=format&fit=crop&w=800&q=80",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      category: "lessons",
      date: "1446/02/08",
      views: 2190,
      featured: false
    }
  ],

  schedule: [
    {
      id: "s1",
      dayAr: "السبت",
      dayHa: "Asabar (Saturday)",
      dayEn: "Saturday",
      time: "Bayan Sallar Asr (4:30 PM)",
      subjectAr: "العقيدة (شرح كتاب التوحيد)",
      subjectHa: "Aqeedah (Sharhin Kitabut Tauhid)",
      subjectEn: "Aqeedah (Kitab at-Tawheed)",
      teacherAr: "أستاذ العقيدة بالمركز",
      teacherHa: "Malamin Aqeedah",
      teacherEn: "Sheikh of Aqeedah",
      locationAr: "قاعة المركز الرئيسية / وبث مباشر",
      locationHa: "Babban Dakin Taro na Markazi & Watsawa Kai Tsaye",
      locationEn: "Main Center Hall & Live Stream"
    },
    {
      id: "s2",
      dayAr: "الأحد",
      dayHa: "Lahadi (Sunday)",
      dayEn: "Sunday",
      time: "Bayan Sallar Magrib (7:00 PM)",
      subjectAr: "الفقه (شرح زاد المستقنع)",
      subjectHa: "Fiqhu (Sharhin Zadul Mustaqni')",
      subjectEn: "Fiqh (Zad al-Mustaqni')",
      teacherAr: "أستاذ الفقه وأصوله",
      teacherHa: "Malamin Fiqhu",
      teacherEn: "Sheikh of Fiqh",
      locationAr: "مسجد المركز",
      locationHa: "Masallacin Markazi",
      locationEn: "Center Mosque"
    },
    {
      id: "s3",
      dayAr: "الثلاثاء",
      dayHa: "Talata (Tuesday)",
      dayEn: "Tuesday",
      time: "Bayan Sallar Asr (4:30 PM)",
      subjectAr: "الحديث (شرح عمدة الأحكام)",
      subjectHa: "Hadisi (Sharhin Umdatul Ahkam)",
      subjectEn: "Hadith (Umdat al-Ahkam)",
      teacherAr: "أستاذ علم الحديث",
      teacherHa: "Malamin Hadisi",
      teacherEn: "Sheikh of Hadith",
      locationAr: "قاعة الشيخ محمد بن إبراهيم",
      locationHa: "Dakin Taro na Sheikh Muhammad",
      locationEn: "Sheikh Muhammad Hall"
    },
    {
      id: "s4",
      dayAr: "الخميس",
      dayHa: "Alhamis (Thursday)",
      dayEn: "Thursday",
      time: "Bayan Sallar Magrib (7:00 PM)",
      subjectAr: "التفسير (تفسير آيات الأحكام)",
      subjectHa: "Tafseeri (Ayoyin Hukunce-hukunce)",
      subjectEn: "Tafsir of Quranic Verses",
      teacherAr: "أستاذ التفسير",
      teacherHa: "Malamin Tafseer",
      teacherEn: "Sheikh of Tafsir",
      locationAr: "مسجد المركز / وبث مباشر",
      locationHa: "Masallacin Markazi & Kai Tsaye",
      locationEn: "Center Mosque & Live Stream"
    },
    {
      id: "s5",
      dayAr: "الجمعة",
      dayHa: "Juma'a (Friday)",
      dayEn: "Friday",
      time: "Kafin Sallar Juma'a & Bayan Asr",
      subjectAr: "خطبة الجمعة + جلسة فتاوى واستشارات",
      subjectHa: "Huduɓar Juma'a & Zaman Fatawoyi da Amsoshin Tambayoyi",
      subjectEn: "Friday Khutbah & Q&A Fatawa Session",
      teacherAr: "أعضاء اللجنة العلمية بالمركز",
      teacherHa: "Kwamitin Malamai na Markazi",
      teacherEn: "Center Scholarly Committee",
      locationAr: "جامع المركز",
      locationHa: "Babban Masallacin Juma'a na Markazi",
      locationEn: "Grand Center Mosque"
    }
  ]
};

if (typeof window !== "undefined") {
  window.MARKAZ_DATA = INITIAL_DATA;
}
